### ISSUE TITLE
More informative show names!

### ISSUE THREAD

**Issue by josephfinlayson** [redbadger/radiobadger.com#13]
I'm trying to work out which of the podcasts to sync to my iphone. I'm only interested in tech heavy podcasts - it's very difficult to do quickly.

tl;dr -> Less fun, More functional.

**Comment by robbiemccorkell** [comment]
Hi Joseph, thanks for listening!

We figured that since we talk about so many different topics in the show it would be hard to summarise in the title. So we try to have super informative descriptions on every show we put out. Obviously that's not quite as quick to see as the title, but I hope it helps.

**Comment by josephfinlayson** [comment]
Alright, I forgive you. I really enjoy the show!

**Comment by robbiemccorkell** [comment]
Awesome, thanks!
